### ISSUE TITLE
More installation informations | No module named '_lzma'

### ISSUE THREAD

**Issue by antiqrom** [Theo-SAMINADIN-td/NukeDepthCrafter#2]
![yXDIVLOCoG](https://github.com/user-attachments/assets/c13138fd-3e37-4706-bb01-c9111f5feae9)

Hello, got this error, help me pls

**Comment by Theo-SAMINADIN-td** [comment]
Hi @antiqrom ,
Could you describe a little more how you installed Depth Crafter and its dependencies?

From what I can see here, you have installed Torchvision. It could come from that. 

For now, I can see two options: 
1. Your error seems similar to [this issue](https://github.com/ultralytics/yolov5/issues/1298#issue-736860942), so you can try to install [backports.lzma](https://pypi.org/project/backports.lzma/).
2. Reinstall torch without torchvision: `pip uninstall torch torchvision` then `pip install torch==2.0.1+cu118 --index-url https://download.pytorch.org/whl/cu118`

**Comment by Ireneyhy** [comment]
i'm having the same issue. It seems the python shipped with nuke doesn't include the lzma module.

**Comment by Theo-SAMINADIN-td** [comment]
Hi, sorry for the late answer.

I could reproduce your error by installing Pytorch and Torchvision like that `pip install torch==2.0.1+cu118 torchvision --index-url https://download.pytorch.org/whl/test/cu118`

Then Nuke is returning me your error.
> File "C:\Program Files\Nuke15.1v3\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named '_lzma'

I have managed to solve it by uninstalling Torchvision.
`pip uninstall torchvision`
Then Nuke should launch.

**Comment by rama19998** [comment]
@Theo-SAMINADIN-td  hi I’ve recently started exploring Depthcrafter for Nuke, but I’m having a bit of trouble with the installation process. I was wondering if you might be able to create a tutorial. I would really appreciate any help or resources you can provide, and I’m sure it would be valuable to others as well.

Thank you so much for your time and consideration!

**Comment by spade-asakawa** [comment]
@Theo-SAMINADIN-td 

i'm trying to install the plug-in but this error keeps happening and stops me from launching nuke,could you please inform us how to solve it ?

we tried installing numpy but this error happened anyway

```
NukeX 15.0v2, 64 bit, built Nov 11 2023.
Copyright (c) 2023 The Foundry Visionmongers Ltd.  All Rights Reserved.

Traceback (most recent call last):
  File "C:/Users/asakawa/.nuke/Nuke13_later/VFX_Tools/Plugin/NukeDepthCrafter/menu.py", line 1, in <module>
    from nukedc import CreateDCNode, UpdatePath, GenerateDepth
  File "C:\Program Files\Nuke15.0v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/asakawa/.nuke/Nuke13_later/VFX_Tools/Plugin/NukeDepthCrafter\nukedc.py", line 3, in <module>
    from DepthCrafterPlugin.utils import *
  File "C:\Program Files\Nuke15.0v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/asakawa/.nuke/Nuke13_later/VFX_Tools/Plugin/NukeDepthCrafter\DepthCrafterPlugin\utils.py", line 7, in <module>
    import numpy as np
  File "C:\Program Files\Nuke15.0v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'numpy'
```

**Comment by hosseinbehrad** [comment]
hello 
After hours of effort, I found the problem with the help of my dear friend Mohsen Jaldi and it was solved

After downloading the files, you must organize the folders, they are not correct by default.
Please arrange the files according to the image after the given file

warning
If you already have the init.py and menu.py files in your nook folder, be careful not to repost because the previous plugins will not be loaded anymore. (Just add the text inside these to your file)

![image](https://github.com/user-attachments/assets/e51d9152-2598-4ec2-8aee-80738dc4a3c0)

https://github.com/Theo-SAMINADIN-td/NukeDepthCrafter/raw/main/images/Tree.jpg

![image](https://github.com/user-attachments/assets/dce04bee-d98d-4f2b-8dd8-ef0739313f51)

The files in yellow are related to this plugin



Follow the next steps according to the guide to reach this stage

![image](https://github.com/user-attachments/assets/947d5f26-0730-4a08-bffe-5a08e2418827)

After doing this step, a folder is created in your C drive, the name of the folder is "path"

for 4 step
![image](https://github.com/user-attachments/assets/c417f573-2c81-4b41-a02d-61aafa7992d4)

You must open the init.py and change "#nuke.pluginAddPath(r"path/to/your/PATH/site-packages")" to nuke.pluginAddPath(r"C:/path/to/new/virtual/environment/Lib/site-packages")

![image](https://github.com/user-attachments/assets/7a559b16-150c-4819-871f-0a1db8c098a2)

As you can see, the address of the site-packages is here

**Comment by hosseinbehrad** [comment]
If your old nukes version encounter errors
You should put this plugin in this path of the Nuke plugins instead of the Nuke folder (C:\Program Files\Nuke15.0v4\plugins)
